### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by sweetpants** [robertklep/nefit-easy-http-server#12]
Hi,

Since today I get XMPP authentication failures when starting the easy-server (3.1.2). I hav already upgraded node.js (v6.14.2) and npm (3.10.10), but keep getting these when staring the easy-server. The android app is just working fine and I have check the credentials and they look ok (never changed them)

What can I do to investigate this?

Regards, Harry

**Comment by robertklep** [comment]
I'm getting the same on iOS. I noticed earlier today that my Easy wasn't connected to the cloud server, and it sounds like they have pushed an update to the server that is blocking my client.

I'll check and see if I can find out what's going on. Otherwise, I'll try and contact Nefit about this.

**Comment by sweetpants** [comment]
Thanx

**Comment by robertklep** [comment]
Quick update: got it working again. Because it required some rather big changes, it may take a few hours before I can push an update, since I have to make sure everything is still working okay :)

**Comment by Xoem** [comment]
Got here because I was experiencing the same issue, just want to say thanks it is already addressed.

**Comment by sweetpants** [comment]
That would be great and appreciated. I pretty much rely on this peace of SW to control my CV installation (with Domoticz). Lucky it's warm outside now.

**Comment by robertklep** [comment]
Not looking so great at the moment: I'm able to retrieve settings, but not set them. The backend is returning an error when I do.

So may actually take more time than I had anticipated 🙁

**Comment by edwinligthart** [comment]
how do you update?
I'm running easy-server on raspbian

Tried several options to update but version stays at 3.1.2

sudo npm update  nefit-easy-http-server -g
-and-
sudo npm i  nefit-easy-http-server -g

**Comment by edwinligthart** [comment]
Oke, how do I make that link?

**Comment by robertklep** [comment]
Just wait a while and try installing it again, don't start replacing links (which is likely caused by a different version of Node rather than the new version of `nefit-easy-http-server`).

**Comment by edwinligthart** [comment]
OK, i'll try in a while

**Comment by edwinligthart** [comment]
Indeed, patience was the key ;-)

**Comment by The-M-Peror** [comment]
Same issue, but everything up and running again now! Thank you very much for that quick fix.

**Comment by FrankvanCoeverden** [comment]
I completely missed this topic yesterday. 

Thanks Robert for the quick solution.

**Comment by CaptainFS** [comment]
Thanks Robert for fixing things, however I run into an error:
$ easy-server -v
module.js:549
    throw err;
    ^

Error: Cannot find module '@xmpp/connection'
etc.

I tried reinstalling, cleaned old versions, still got this error.

**Comment by sweetpants** [comment]
Latest version should be 4.0.1 of the easy-server

**Comment by robertklep** [comment]
@CaptainFS which version of Node? `node -v`

**Comment by CaptainFS** [comment]
Well the raspberry installed the latest 8.11.2, but before I had a v 7.x (can't remember the exact version) with the same problem.

**Comment by robertklep** [comment]
Sounds like (part of) the installation might have failed. Are you sure there weren't any errors when you installed the server package?

**Comment by robertklep** [comment]
I don't think `npm update` will work, you need to do a full install.

Also, make sure that when using `sudo` the proper Node version is being used, which isn't always the case.

* `sudo node -v` should show it's Node v6 or higher
* `sudo npm config get prefix` should show `/usr`
* if you intend to run the server as a regular user, both commands should show the exact same output without the `sudo` prefixed to them

**Comment by CaptainFS** [comment]
Solved as 'user error'. I did remove every NPM and Node/NodeJS file I could find, thereafter installed NPM with `sudo aptitude install npm` which downgraded NodeJS to a 0.1xxx version. Thereafter `sudo apt-get update` and a `sudo apt-get dist-upgrade`. That installed NPM 5.6.0 (i had 2.x), this NPM installed the Easy-Server correctly.

**Comment by CaptainFS** [comment]
sporadicly it stops, if you restart it works again.

**Comment by CaptainFS** [comment]
sporadicly it stops, if you restart it works again.

**Comment by robertklep** [comment]
@CaptainFS I'm testing a possible fix (robertklep/nefit-easy-core#14), the issue it related to the connection to the Easy being lost and not being picked up again when it's back online.

However, it's proving to be difficult to debug (also not helped by the Nefit/Bosch backend being offline quite a lot in recent days).

**Comment by Epimedium** [comment]
Hi, I have some difficulties creating a docker container for RPI. I've downloaded the latest docker files and tried to create a container for a RPI3. This is the result:
pi@raspberrypi:~/Nefit $ sudo docker build -t nefit .
Sending build context to Docker daemon  78.14MB
Step 1/10 : FROM resin/rpi-raspbian:latest
 ---> f542b3baa5b3
Step 2/10 : ENTRYPOINT []
 ---> Running in f52e9282308a
Removing intermediate container f52e9282308a
 ---> bfb97096fdf0
Step 3/10 : FROM node:9.11.1-alpine
9.11.1-alpine: Pulling from library/node
no matching manifest for linux/arm in the manifest list entries

I have installed node and NMP the way is was descibed above:
pi@raspberrypi:~/Nefit $ npm -v
5.6.0
pi@raspberrypi:~/Nefit $ node -v
v9.11.1
pi@raspberrypi:~/Nefit $ 

The nefit easy server was running fine untill the above described problems started.
Can you give me some advice on how to get the nefit easy server running?

Thanks!

**Comment by robertklep** [comment]
@Epimedium I don't see any specific errors related to the Nefit Easy server, it looks like your error is related to Docker specifically, and I don't know enough about Docker to help you.

**Comment by isty1974** [comment]
npm -v
6.4.1
node -v
v10.11.0
easy-server -v
5.0.2

pi@raspberrypi:~ $ sudo easy-server --serial=<> --access-key=<> --password=<> -V
XMPP authentication failure

wtf?

**Comment by robertklep** [comment]
@isty1974 `nefit-easy-http-server` is specific to Nefit Easy and compatible devices. It doesn't sound like your device is compatible.

You could try this module: https://github.com/robertklep/bosch-xmpp

If that doesn't work: do you have a mobile app that can be used to control the device? If so, what's the name of that app? Perhaps I can try and add support for it that way.

**Comment by isty1974** [comment]
@robertklep : Mobile App is working fine. iPhone: Bosch EasyRemote same as Buderus MyDevice app.
also working with it, because the same hardware with changed cover, tested.

XMPP Installed. Export for variables is done.

pi@raspberrypi:~ $ bosch-xmpp nefit get /system/systemType _or  bosch-xmpp ivt get /gateway/versionFirmware_
Unhandled rejection XMPP authentication failure

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (XMPP authentication failure)
    at Client.emit (events.js:171:17)
    at Client._handleAuthState (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-client/lib/Client.js:295:10)
    at Client._handleStanza (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-client/lib/Client.js:233:12)
    at Client.onStanza (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at Connection.emit (events.js:182:13)
    at Connection.onStanza (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at StreamParser.emit (events.js:182:13)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/bosch-xmpp/node_modules/@xmpp/streamparser/index.js:69:14)
    at SaxLtx.emit (events.js:182:13)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/bosch-xmpp/node_modules/ltx/lib/parsers/ltx.js:39:12)
    at SaxLtx.write (/usr/local/lib/node_modules/bosch-xmpp/node_modules/ltx/lib/parsers/ltx.js:151:18)
    at StreamParser.write (/usr/local/lib/node_modules/bosch-xmpp/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/usr/local/lib/node_modules/bosch-xmpp/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at TLSSocket.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)

**So, in FHEM( as km200 is working fine.**

_/dhwCircuits/dhw1/actualTemp
--
/dhwCircuits/dhw1/charge
/dhwCircuits/dhw1/chargeDuration
/dhwCircuits/dhw1/currentSetpoint
/dhwCircuits/dhw1/holidayMode/activated
/dhwCircuits/dhw1/operationMode
/dhwCircuits/dhw1/singleChargeSetpoint
/dhwCircuits/dhw1/status
/dhwCircuits/dhw1/switchPrograms/A/1-Mo
/dhwCircuits/dhw1/switchPrograms/A/2-Tu
/dhwCircuits/dhw1/switchPrograms/A/3-We
/dhwCircuits/dhw1/switchPrograms/A/4-Th
/dhwCircuits/dhw1/switchPrograms/A/5-Fr
/dhwCircuits/dhw1/switchPrograms/A/6-Sa
/dhwCircuits/dhw1/switchPrograms/A/7-Su
/dhwCircuits/dhw1/waterFlow
/dhwCircuits/dhw1/workingTime
/gateway/DateTime
/gateway/instAccess
/gateway/instWriteAccess
/gateway/logging/userAcceptance
/gateway/openIPAccess
/gateway/update/status
/gateway/uuid
/gateway/versionFirmware
/gateway/versionHardware
/heatSources/CHpumpModulation
/heatSources/ChimneySweeper
/heatSources/actualCHPower
/heatSources/actualDHWPower
/heatSources/actualModulation
/heatSources/actualPower
/heatSources/actualSupplyTemperature
/heatSources/applianceSupplyTemperature
/heatSources/burnerModulationSetpoint
/heatSources/burnerPowerSetpoint
/heatSources/chimneyTemperature
/heatSources/energyMonitoring/consumption
/heatSources/energyMonitoring/correctionFactor
/heatSources/energyMonitoring/maxTankLevel
/heatSources/energyMonitoring/minTankLevel
/heatSources/energyMonitoring/startDateTime
/heatSources/energyMonitoring/tankLevel
/heatSources/flameCurrent
/heatSources/flameStatus
/heatSources/gasAirPressure
/heatSources/hs1/actualModulation
/heatSources/hs1/actualPower
/heatSources/hs1/energyReservoir
/heatSources/hs1/flameStatus
/heatSources/hs1/fuel/caloricValue
/heatSources/hs1/fuel/density
/heatSources/hs1/fuelConsmptCorrFactor
/heatSources/hs1/info/01/Id
/heatSources/hs1/info/01/No
/heatSources/hs1/info/01/Tok
/heatSources/hs1/info/01/Ver
/heatSources/hs1/nominalFuelConsumption
/heatSources/hs1/reservoirAlert
/heatSources/hs1/type
/heatSources/info/01/Id
/heatSources/info/01/No
/heatSources/info/01/Tok
/heatSources/info/01/Ver
/heatSources/nominalCHPower
/heatSources/numberOfStarts
/heatSources/powerSetpoint
/heatSources/returnTemperature
/heatSources/supplyTemperatureSetpoint
/heatSources/systemPressure
/heatSources/workingTime/centralHeating
/heatSources/workingTime/secondBurner
/heatSources/workingTime/totalSystem
/heatingCircuits/hc1/activeSwitchProgram
/heatingCircuits/hc1/actualSupplyTemperature
/heatingCircuits/hc1/currentRoomSetpoint
/heatingCircuits/hc1/fastHeatupFactor
/heatingCircuits/hc1/holidayMode/activated
/heatingCircuits/hc1/manualRoomSetpoint
/heatingCircuits/hc1/operationMode
/heatingCircuits/hc1/pumpModulation
/heatingCircuits/hc1/roomtemperature
/heatingCircuits/hc1/status
/heatingCircuits/hc1/supplyTemperatureSetpoint
/heatingCircuits/hc1/switchProgramMode
/heatingCircuits/hc1/switchPrograms/A/1-Mo
/heatingCircuits/hc1/switchPrograms/A/2-Tu
/heatingCircuits/hc1/switchPrograms/A/3-We
/heatingCircuits/hc1/switchPrograms/A/4-Th
/heatingCircuits/hc1/switchPrograms/A/5-Fr
/heatingCircuits/hc1/switchPrograms/A/6-Sa
/heatingCircuits/hc1/switchPrograms/A/7-Su
/heatingCircuits/hc1/switchPrograms/B/1-Mo
/heatingCircuits/hc1/switchPrograms/B/2-Tu
/heatingCircuits/hc1/switchPrograms/B/3-We
/heatingCircuits/hc1/switchPrograms/B/4-Th
/heatingCircuits/hc1/switchPrograms/B/5-Fr
/heatingCircuits/hc1/switchPrograms/B/6-Sa
/heatingCircuits/hc1/switchPrograms/B/7-Su
/heatingCircuits/hc1/temperatureLevels/comfort2
/heatingCircuits/hc1/temperatureLevels/eco
/heatingCircuits/hc1/temperatureRoomSetpoint
/heatingCircuits/hc1/temporaryRoomSetpoint
/heatingCircuits/hc2/activeSwitchProgram
/heatingCircuits/hc2/actualSupplyTemperature
/heatingCircuits/hc2/currentRoomSetpoint
/heatingCircuits/hc2/holidayMode/activated
/heatingCircuits/hc2/manualRoomSetpoint
/heatingCircuits/hc2/operationMode
/heatingCircuits/hc2/pumpModulation
/heatingCircuits/hc2/roomtemperature
/heatingCircuits/hc2/status
/heatingCircuits/hc2/supplyTemperatureSetpoint
/heatingCircuits/hc2/switchProgramMode
/heatingCircuits/hc2/switchPrograms/A/1-Mo
/heatingCircuits/hc2/switchPrograms/A/2-Tu
/heatingCircuits/hc2/switchPrograms/A/3-We
/heatingCircuits/hc2/switchPrograms/A/4-Th
/heatingCircuits/hc2/switchPrograms/A/5-Fr
/heatingCircuits/hc2/switchPrograms/A/6-Sa
/heatingCircuits/hc2/switchPrograms/A/7-Su
/heatingCircuits/hc2/switchPrograms/B/1-Mo
/heatingCircuits/hc2/switchPrograms/B/2-Tu
/heatingCircuits/hc2/switchPrograms/B/3-We
/heatingCircuits/hc2/switchPrograms/B/4-Th
/heatingCircuits/hc2/switchPrograms/B/5-Fr
/heatingCircuits/hc2/switchPrograms/B/6-Sa
/heatingCircuits/hc2/switchPrograms/B/7-Su
/heatingCircuits/hc2/temperatureLevels/comfort2
/heatingCircuits/hc2/temperatureLevels/eco
/heatingCircuits/hc2/temperatureRoomSetpoint
/heatingCircuits/hc2/temporaryRoomSetpoint
/system/appliance/CHpumpModulation
/system/appliance/ChimneySweeper
/system/appliance/actualPower
/system/appliance/actualSupplyTemperature
/system/appliance/flameCurrent
/system/appliance/gasAirPressure
/system/appliance/nominalBurnerLoad
/system/appliance/numberOfStarts
/system/appliance/powerSetpoint
/system/appliance/systemPressure
/system/appliance/workingTime/centralHeating
/system/appliance/workingTime/secondBurner
/system/appliance/workingTime/totalSystem
/system/brand
/system/bus
/system/healthStatus
/system/heatSources/hs1/actualModulation
/system/heatSources/hs1/actualPower
/system/heatSources/hs1/energyReservoir
/system/heatSources/hs1/fuel/caloricValue
/system/heatSources/hs1/fuel/density
/system/heatSources/hs1/fuelConsmptCorrFactor
/system/heatSources/hs1/nominalFuelConsumption
/system/heatSources/hs1/reservoirAlert
/system/holidayModes/hm1/dhwMode
/system/holidayModes/hm1/hcMode
/system/holidayModes/hm1/startStop
/system/holidayModes/hm2/dhwMode
/system/holidayModes/hm2/hcMode
/system/holidayModes/hm2/startStop
/system/holidayModes/hm3/dhwMode
/system/holidayModes/hm3/hcMode
/system/holidayModes/hm3/startStop
/system/holidayModes/hm4/dhwMode
/system/holidayModes/hm4/hcMode
/system/holidayModes/hm4/startStop
/system/holidayModes/hm5/dhwMode
/system/holidayModes/hm5/hcMode
/system/holidayModes/hm5/startStop
/system/info/01/Id
/system/info/01/No
/system/info/01/Tok
/system/info/01/Ver
/system/info/02/Id
/system/info/02/No
/system/info/02/Tok
/system/info/02/Ver
/system/info/03/Id
/system/info/03/No
/system/info/03/Tok
/system/info/03/Ver
/system/info/04/Id
/system/info/04/No
/system/info/04/Tok
/system/info/04/Ver
/system/info/05/Id
/system/info/05/No
/system/info/05/Tok
/system/info/05/Ver
/system/minOutdoorTemp
/system/sensors/temperatures/chimney
/system/sensors/temperatures/hotWater_t2
/system/sensors/temperatures/outdoor_t1
/system/sensors/temperatures/return
/system/sensors/temperatures/supply_t1
/system/sensors/temperatures/supply_t1_setpoint
/system/sensors/temperatures/switch
/system/systemType_

**Comment by robertklep** [comment]
I'll have to take a closer look at FHEM's implementation, it could be yet another completely different authentication/encryption setup. But for right now, it means that both this project and `bosch-xmpp` don't support the device.

**Comment by robertklep** [comment]
@isty1974 it looks like the FHEM code is similar to the "ivt" client code. Could you try and see if removing the "-" characters from the access key allows you to log in?

From what I know, the value that you should pass as "serial number" is a 9-digit number.

**Comment by isty1974** [comment]
WORKING! SAMPLE:
pi@raspberrypi:~ $ bosch-xmpp --serial=<nnnnnnnnn> --access-key=<$$$$$$$$$$$$$$$$> --password=<your own> ivt get /system/systemType
{"id":"/system/systemType","type":"stringValue","writeable":0,"recordable":0,"value":"NSC_ICOM_GATEWAY","allowedValues":["NSC_ICOM_GATEWAY"]}

**Comment by robertklep** [comment]
@isty1974 what did you change specifically to get it working?

**Comment by isty1974** [comment]
just removed MINUS signs "-" from access-key chain :) however on the case there is officially with minuses...

**Comment by robertklep** [comment]
@isty1974 yeah I remembered someone else having the same problem. I'll add some code that removes those characters automatically, I believe that's what the official app does as well.

**Comment by isty1974** [comment]
@robertklep THANK YOU SO MUCH, Last question: Can cou help me to add it to Domoticz? :)

**Comment by robertklep** [comment]
@isty1974 I have no experience with Domoticz, so I can't help you :(

I do know that the Nefit Easy support for Domoticz is based on `nefit-easy-http-server`, and `bosch-xmpp` can work in a similar way (it also has a built-in server), but it does have a different set of endpoints. Perhaps the person that implemented Nefit Easy support for Domoticz can help you out? Or someone on its forum.

**Comment by isty1974** [comment]
just a note: 
**bosch-xmpp ivt get /system/brand**

_{"id":"/system/brand","type":"stringValue","writeable":0,"recordable":0,"value":"unknown","allowedValues":["unknown","Bosch","Junkers","Buderus","Nefit","Sieger","Tata","Dakon","Elm","Boulter","Vulcano","Worcester","British Gas","IVT","Geminox","Neckar","Zeus","Milton"]}_

:it could mean, more vendors IP modules already supported.

**Comment by robertklep** [comment]
@isty1974 even though "Nefit" is listed there, it doesn't work with the "ivt" driver, so I'm hesitant to copy that list of brand names to the documentation as being supported.

If more people test the code with their devices, and they report success, I'll add them as being confirmed working :)
