### ISSUE TITLE
CPU usage is getting higher an higher

### ISSUE THREAD

**Issue by pa3gmi** [robertklep/nefit-easy-http-server#17]
Hi I have the following problem I use a Raspberry B with msata disk running Domoticz so far no problem. But when I install Nefit Easy(it works great, all 10 sensors) the processor activity is higher and higher beginning with 1.5 % and every day 1 % higher. I have looked to the tasks and the Node task is making the high activity. I am not a Unix expert, and 69 years old, never to old to learn something. But I would ask, have you an idea?  I use node -v (versie 10.4.1)
npm -v (6.1.0)  easy-server -v (4.0.1)  pm2 -v=2.10.4  and Raspbian stretch kernel 4.14
Thanks for the work already done on this project.
Regards, Rien.

**Comment by robertklep** [comment]
The processor activity is dependent on how often the server has to handle a request (i.e. update the Nefit Easy status): when it's updating, a higher CPU usage is expected. But when it's idle, waiting for new requests, its CPU usage should be relatively low.

I have no idea why it would steadily increase over time, though. It's not something that I've experienced myself, but I'm not running the server on an RPi (it's running on a Linux server, though).

**Comment by edwinligthart** [comment]
CPU and memory usage are realy increased after the last updates of the nefit-easy-server.  From less then 2,5% to an avarage of 10%. That means that peaks are really high in comparison te earlier versions.

I''m running on an RPi also.

**Comment by robertklep** [comment]
What are those values based on? Per process, or total CPU usage?

Since the update of the Nefit backend (which coincides with the release of a new version of the HTTP server), its using a different (more CPU-intensive) authentication mechanism. Combined with the unstability of the backend since that time, the additional CPU-cycles may be caused by repeated reconnects.

Alternatively, the different XMPP library that is being used may require more CPU-cycles, but I haven't really noticed a massive increase of CPU myself (however, I don't run it on an RPi).

**Comment by edwinligthart** [comment]
The image above is the avarage CPU usage of the device. I do not have a per-process graph.

**Comment by pa3gmi** [comment]
Average CPU usage on my pi is at the moment 4% but when I look with Htop I see sometimes the easy-server with 53 to 70% sometimes 2 or more connects after each other. What strange is that after a reboot this is not the case but it seems wind up somewhere. When I start after a reboot the CPU usage is 1.5% after that it will increase slowly.

**Comment by robertklep** [comment]
Are you all using Domoticz? How does it handle stalled requests? Does it always wait for a previous request to finish (either properly or through a timeout) before it schedules a new request?

**Comment by pa3gmi** [comment]
I use Domoticz, but I know not how it handle requests, I send you here a logfile from domoticz perhaps you can see.
 2018-06-21 12:54:48.345 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:54:48.538 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:54:52.251 (RFlink) Rain (Oregon Rain2)
2018-06-21 12:55:14.298 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:55:14.309 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:55:14.317 (Gateway) General/Barometer (Baro)
2018-06-21 12:55:19.017 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:55:19.021 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:55:19.217 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:55:19.588 (Nefit server) General/Pressure (Waterdruk CV Nefit)
2018-06-21 12:55:19.804 (Nefit server) Temp (Outside Temperature)
2018-06-21 12:55:23.865 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:55:24.104 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:55:30.809 (RFlink) Temp (Buiten temperatuur poort)
2018-06-21 12:55:39.252 (RFlink) Rain (Oregon Rain2)
2018-06-21 12:55:42.973 (Gateway) Temp (Temp)
2018-06-21 12:55:42.987 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:55:50.089 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:55:50.093 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:55:50.287 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:56:11.664 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:56:11.675 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:56:11.682 (Gateway) General/Barometer (Baro)
2018-06-21 12:56:18.813 (RFlink) Temp (Buiten temperatuur poort)
2018-06-21 12:56:20.762 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:56:20.766 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:56:20.961 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:56:23.155 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:56:23.395 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:56:26.252 (RFlink) Rain (Oregon Rain2)
2018-06-21 12:56:40.341 (Gateway) Temp (Temp)
2018-06-21 12:56:40.355 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:56:51.433 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:56:51.438 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:56:51.630 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:57:02.007 (Nefit server) P1 Smart Meter (Gashoeveelheid Nefit)
2018-06-21 12:57:06.813 (RFlink) Temp (Buiten temperatuur poort)
2018-06-21 12:57:09.030 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:57:09.044 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:57:09.052 (Gateway) General/Barometer (Baro)
2018-06-21 12:57:13.249 (RFlink) Rain (Oregon Rain2)
2018-06-21 12:57:22.295 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:57:22.300 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:57:22.443 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:57:22.499 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:57:22.679 (Diversen dummy) General/Voltage (Close-in boiler spanning)
2018-06-21 12:57:37.709 (Gateway) Temp (Temp)
2018-06-21 12:57:37.724 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:57:52.967 (Nefit server) Thermostat (Ingestelde kamertemperatuur Nefit)
2018-06-21 12:57:52.971 (Nefit server) Temp (Kamer temperatuur Nefit)
2018-06-21 12:57:53.172 (Nefit server) Temp (Tapwater temperatuur Nefit)
2018-06-21 12:57:54.816 (RFlink) Temp (Buiten temperatuur poort)
2018-06-21 12:58:00.250 (RFlink) Rain (Oregon Rain2)
2018-06-21 12:58:06.400 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:58:06.411 (Gateway) Temp + Humidity + Baro (TempHumBaro boven)
2018-06-21 12:58:06.421 (Gateway) General/Barometer (Baro)

© 2012-2

**Comment by edwinligthart** [comment]
yes, this is domoticz, I have nog logging of the connection state

**Comment by pa3gmi** [comment]
With the latest stable version of Domoticz it seems that the wind up from the processor is a lot less.

**Comment by pa3gmi** [comment]
I was to early with my conclusion, in the beginning it seems better, but now it is as usual.

**Comment by robertklep** [comment]
I'm afraid someone familiar with Domoticz internals has to take a look at this, because I'm all out of ideas.

To give an idea on where I'm at now:
* I've ruled out that merely running the HTTP-server is the problem, because I've been running one for weeks now and haven't noticed any increasing CPU-usage;
* Having the HTTP-server perform periodic (30s) updates: the HTTP-server mentioned in the previous item did just that. Not a problem.
* Running the core code for a long time on restricted hardware: I have a Homey that's running the Nefit Easy app, which also performs periodic requests to the backend (using the same core code as the HTTP server). My Homey typically has an uptime measured in weeks. Not a problem. Homey is also more restricted in terms of hardware than an RPi, so that's not a cause either.
* All issues regarding increasing CPU usage are from people running Domoticz, so I think it's fair to say that there's some weird interaction between Domoticz and the HTTP server that's causing this.

I'm not familiar with Domoticz at all, so I have no idea how it handles requests to the HTTP-server (including timeouts, scheduling, error-handling, etc).

**Comment by pa3gmi** [comment]
Yes I think you are right, I go further on the Domoticz forum to try getting a solution.
Tanks fot your help.

**Comment by MickMack82** [comment]
Maybe I've found something in the errorlog of PM2 we can use to solve the issue.
The errorlog of PM2 is flooded with the following message:

```
(node:29044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at Promise (/usr/lib/node_modules/nefit-easy-http-server/node_modules/@xmpp/connection/index.js:307:19)
    at new Promise (<anonymous>)
    at Client.write (/usr/lib/node_modules/nefit-easy-http-server/node_modules/@xmpp/connection/index.js:305:12)
    at Client.send (/usr/lib/node_modules/nefit-easy-http-server/node_modules/@xmpp/connection/index.js:292:17)
    at Client.Connection.send (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:15:15)
    at Client.send (/usr/lib/node_modules/nefit-easy-http-server/node_modules/@xmpp/client-core/lib/Client.js:18:18)
    at Object.queue.add [as promiseGenerator] (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:125:19)
    at Queue._dequeue (/usr/lib/node_modules/nefit-easy-http-server/node_modules/promise-queue/lib/index.js:153:30)
    at /usr/lib/node_modules/nefit-easy-http-server/node_modules/promise-queue/lib/index.js:109:18
    at new Promise (<anonymous>)
    at Queue.add (/usr/lib/node_modules/nefit-easy-http-server/node_modules/promise-queue/lib/index.js:94:16)
    at NefitEasyCommands.queueMessage (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:122:23)
    at NefitEasyCommands.send (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:197:17)
    at queueMessage.catch.e (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:201:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3088)
```

No Idea what the problem is... but something isn't going as expected.
I also experience more and more CPU and memory usage over time with domoticz. Maybe nodejs is encoutering a loop which takes more and more resources like a memory leak? Also posted this on the domoticz forum.

**Comment by robertklep** [comment]
@MickMack82 that error is one that we've been trying to fix.

I posted instructions on installing a debug version of the HTTP server [here](https://github.com/robertklep/nefit-easy-core/issues/14#issuecomment-398140079). Perhaps you can try and run that to see how it performs for you.

**Comment by MickMack82** [comment]
Ok, installed the debug version. Checked if it is using the correct core, and it is.
I'll let it run for a couple of days and see how it preforms. I'll let you know.

**Comment by robertklep** [comment]
Please try installing the latest version, `nefit-easy-http-server@5.0.1`.

Due to other issues, I reverted back to the old XMPP client, which seems to have solved those other issues. Hopefully this issue will also have been solved.

Feel free to reopen this issue if the problem persists.

**Comment by pa3gmi** [comment]
Hi Robert,

This is working for me, no longer CPU load problems.
Thanks!
Rien.

**Comment by GeitjeG** [comment]
Thanks Robert and others, for me it is working like a charm now! (Domoticz on RPI) Now for 24 hours, wil see wether it will last for some weeks, but my http errors are gone already.

**Comment by edwinligthart** [comment]
Looks much better now
![image](https://user-images.githubusercontent.com/39744483/44545685-0b917000-a716-11e8-922e-d97fa63be485.png)

**Comment by edwinligthart** [comment]
Also memory usage is heavely reduced
![image](https://user-images.githubusercontent.com/39744483/44570000-8c835280-a77c-11e8-8590-8510b449a5a5.png)

**Comment by robertklep** [comment]
@edwinligthart yeah, looks like the newer XMPP client suffers from [memory leaks](https://github.com/xmppjs/xmpp.js/issues/546). Another reason why I reverted back to the previous version.
