### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by sweebee** [robertklep/nefit-easy-http-server#2]
I get the following error when starting:

```
/usr/local/lib/node_modules/nefit-easy-http-server/lib/cli/index.js:32
  return client.connect().then(() => {
                                ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by robertklep** [comment]
You need to make sure that the Node.js version that you're using is at least v4.0.0. It looks like you're using an older version.

**Comment by sweebee** [comment]
ah, yes i'm using an older version because of pimatic. Thanks.
