### ISSUE TITLE
Domoticz reports: NefitEasy Error getting http data

### ISSUE THREAD

**Issue by GVries** [robertklep/nefit-easy-http-server#37]
Hi !

Recently I have been getting the error from Domoticz that it cant get any http data. I've found your readme stating the issue around the default SSL protocol, and tried to update the parameters in the /etc/ssl/openssl.cnf file, however these parameters are not at all avaialble in the file:

        MinProtocol = None
        CipherString = DEFAULT

Not with these values, not with any values. I tried adding them, which didnt work, so now I'm back to finding the issue. I do have a recent installation of raspbian on a Pi 3b+.

I did ran: curl http://127.0.0.1:3000/bridge/ecus/rrc/uiStatus
which resulted in:

Error: MAX_RETRIES_REACHED
    at queueMessage.catch.e (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:179:51)
    at tryCatcher (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by robertklep** [comment]
That error isn't caused by the OpenSSL-issue, because it suggests that a successful connection does get made, but the command requests don't get a response from the Easy within the allotted time.

The default is 30 seconds, but you can try and raise it to, say, 120 seconds:
```
$ easy-server --timeout=120 ...
```

But 30 seconds should be plenty. Does the Nefit Easy mobile app work for you?

If so, and raising the timeout doesn't solve the problem, you can run the server in debugging mode and post the debug log here:
```
$ env DEBUG=* easy-server ...
```

**Comment by GVries** [comment]
So sorry for bothering you with this. I just checked and apparently the whole nefit easy was disconnected (from its wall holder). Probably just my kid playing with it. I plugged it back in and now everything works again. 

Again, sorry :)

**Comment by robertklep** [comment]
Haha that explains it! Glad to hear the problem is solved 👍🏻
