### ISSUE TITLE
INVALID RESPONSE when setting temperature

### ISSUE THREAD

**Issue by balk77** [robertklep/nefit-easy-http-server#9]
Hi, I am trying to override the temperature setpoint of the running program (while remaining in clock mode). I have the server running on port 8124 (`curl http://127.0.0.1:8124/api/status` gives proper output)

`curl http://127.0.0.1:8124/bridge/heatingCircuits/hc1/manualTemperatureOverride/temperature -d '{"value":20}' -H 'Content-Type: application/json'` 
gives an error (see below). Can you please help me?

`Error: INVALID_RESPONSE
    at send.then (/usr/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:253:19)
    at tryCatcher (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by balk77** [comment]
Thanks a lot!
